  - platform: command_line
    command: 'python3 /config/scripts/unifi_switch.py'
    command_timeout: 60
    name: unifi_switch
    value_template: '{{ value_json.Ports_used }}'
    unit_of_measurement: Clients
    scan_interval: 120
    json_attributes:
        - Model
        - Temp
        - Activity
        - CPU
        - RAM  
        - Uptime
        - Ports_used      
        - Ports_user
        - Ports_guest
        - Update
  - platform: template
    sensors:  
      unifi_switch_temp:
          value_template: >
              {{ states.sensor.unifi_switch.attributes.Temp }}
          friendly_name_template: Switch Temp
          unit_of_measurement: '℃'
      unifi_switch_activity:
          value_template: >
              {{ states.sensor.unifi_switch.attributes.Activity }}
          unit_of_measurement: 'Mbps'
          friendly_name_template: Switch       
      unifi_switch_ram:
          value_template: >
              {{ states.sensor.unifi_switch.attributes.RAM }}
          unit_of_measurement: '%'
          friendly_name_template: Switch RAM
      unifi_switch_cpu:
          value_template: >
              {{ states.sensor.unifi_switch.attributes.CPU }}
          unit_of_measurement: '%'
          friendly_name_template: Switch CPU   
      unifi_switch_model:
          value_template: >
              {{ states.sensor.unifi_switch.attributes.Model  }}
          friendly_name_template: Model
      unifi_switch_users:
          value_template: >
              {{ states.sensor.unifi_switch.attributes.Ports_user }}
          friendly_name_template: Users
      unifi_switch_guests:
          value_template: >
              {{ states.sensor.unifi_switch.attributes.Ports_guest }}
          friendly_name_template: Guest
      unifi_switch_update:
          value_template: >
              {% if is_state_attr('sensor.unifi_switch', 'Update' , false) %}
                No
              {% else %}
                Available
              {% endif %}
          friendly_name_template: Switch Updates