command_line:
  - sensor:
     command: 'python3 /config/scripts/unifi_ap.py'
     command_timeout: 60
     name: unifi_ap
     value_template: '{{ value_json.Clients }}'
     unit_of_measurement: Clients
     scan_interval: 120
     json_attributes:
         - Guests
         - Clients_wifi0
         - Clients_wifi1
         - Score  
         - CPU
         - RAM
         - Uptime
         - Score_wifi0
         - Score_wifi1
         - Activity
         - Update
sensor:         
  - platform: template
    sensors:  
      unifi_ap_guests:
          value_template: >
              {{ states.sensor.unifi_ap.attributes.Guests }}
          friendly_name_template: Unifi AP Guests    
      unifi_ap_activity:
          value_template: >
              {{ states.sensor.unifi_ap.attributes.Activity }}
          unit_of_measurement: 'Mbps'
          friendly_name_template: Unifi AP Activity      
      unifi_ap_ram:
          value_template: >
              {{ states.sensor.unifi_ap.attributes.RAM }}
          unit_of_measurement: '%'
          friendly_name_template: Unifi AP RAM    
      unifi_ap_cpu:
          value_template: >
              {{ states.sensor.unifi_ap.attributes.CPU }}
          unit_of_measurement: '%'
          friendly_name_template: Unifi AP CPU
      unifi_ap_score:
          value_template: >
              {{ states.sensor.unifi_ap.attributes.Score }}
          friendly_name_template: Unifi AP SCORE
      unifi_ap2_score:
          value_template: >
              {% if is_state_attr('sensor.unifi_ap', 'Score_wifi0' , -1) %}
                N/A
              {% else %}
                {{ states.sensor.unifi_ap.attributes.Score_wifi0 }}.
              {% endif %}
          friendly_name_template: Unifi AP 2.4gHz SCORE
      unifi_ap5_score:
          value_template: >
              {% if is_state_attr('sensor.unifi_ap_', 'Score_wifi1' , -1) %}
                N/A
              {% else %}
                {{ states.sensor.unifi_ap.attributes.Score_wifi1 }}.
              {% endif %}
          friendly_name_template: Unifi AP 5gHz SCORE
      unifi_ap_wifi_devices:
          value_template: >
              {{ states.sensor.unifi_ap.attributes.Clients_wifi0 }}
          friendly_name_template: Unifi AP 2.4gHz Clients
      unifi_ap5ghz_wifi_devices:
          value_template: >
              {{ states.sensor.unifi_ap.attributes.Clients_wifi1 }}
          friendly_name_template: Unifi AP 5gHz Clients
      unifi_ap_update:
          value_template: >
              {% if is_state_attr('sensor.unifi_ap', 'Update' , false) %}
                No
              {% else %}
                Available
              {% endif %}
          friendly_name_template: Unifi AP Updates          
